branch-defaults:
  ajax:
    environment: food-dev
    group_suffix: null
  master:
    environment: food-dev
global:
  application_name: food
  branch: null
  default_ec2_keyname: admin
  default_platform: Python 3.4
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
